name: Compile and test
on: [push]
jobs:
  compile:
    name: Maven compiler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/mcMMO/mcMMO/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_compile_Checkoutrepository_17
    - run: rm starting_compile_Checkoutrepository_17
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: touch starting_compile_Java17setup_19
    - run: rm starting_compile_Java17setup_19
    - name: Java 17 setup
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-package: jdk
        java-version: '17'
    - run: touch starting_compile_CacheMavenpackages_25
    - run: rm starting_compile_CacheMavenpackages_25
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: touch starting_compile_BuildviaMaven_31
    - run: rm starting_compile_BuildviaMaven_31
    - name: Build via Maven
      run: mvn verify -B --file pom.xml
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'mcMMO/.github/workflows/maven/compile'

